README.md
here is a new readme file , with the second pull request.
=> About our project

src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.spec.ts, src/app/diagram/diagram.component.ts, src/app/form/form.component.html, src/app/form/form.component.spec.ts, src/app/form/form.component.ts
I added:
1. new custom shapes
2. two new components: diagram & form
3. a header for the diagram.
=> custom shapes & components

src/app/app.component.html, src/app/diagram/diagram.component.ts, src/app/form/form.component.html, src/styles.css
shapes in the diagram's header can not be moved now.
=> header fixed

src/app/app.component.css, src/app/app.component.html, src/app/app.component.ts, src/app/diagram/diagram.component.ts
=> Add hide/show function button ,fixed diagram and Straight arrow

src/app/Ast.ts, src/app/app.component.html, src/app/app.component.ts, src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.ts, src/app/form/form.component.html, src/app/form/form.component.ts, src/styles.css
=> convert a function to diagram

src/app/app.component.ts, src/app/diagram/diagram.component.ts, src/app/form/form.component.html
=> Repair lines and make them very thin

src/app/Ast.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/diagram/diagram.component.css, src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.ts, src/app/form/form.component.html
=> "each click on a shape makes a code snippet that matches the shape appear under the diagram"

src/app/app.component.ts, src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.ts, src/index.html, tsconfig.json
pop up window appears when the user clicks on one of the shapes
=> pop up windows

src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.ts
when the user clicks on a shape, the shape highlights, and a little red circle appear inside the shape. when the user closes the pop up window that belongs to the shape, the highlight disappear.
=> highlights

src/app/app.component.html, src/app/app.component.ts, src/app/diagram/diagram.component.ts, src/app/form/form.component.html, src/index.html
a better highlight when a user clicks on a shape
=> highlights2

src/app/app.component.html, src/app/app.component.ts, src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.ts, src/index.html
zoom in and zoom out feature to the diagram.
=> zoom in & zoom out feature

src/app/Ast.ts, src/app/diagram/diagram.component.ts
=> Update a drawing function

src/app/Ast.ts, src/app/app.component.ts, src/app/diagram/diagram.component.ts
=> content with the construct itself

src/app/app.component.ts, src/app/diagram/diagram.component.ts, src/app/form/form.component.ts
=> convert button's bug

src/app/app.component.css, src/app/app.component.html, src/app/diagram/diagram.component.css, src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.ts, src/index.html, src/styles.css
=> ui features & bug fixes

src/app/app.component.html, src/app/diagram/diagram.component.css, src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.ts
new similarity ratios, new ctrl feature
=> newCtrlRatio

src/app/app.component.html, src/app/diagram/diagram.component.ts
new preprocess algorithem for the similarity feature
=> preprocess 

src/app/app.component.html, src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.ts
=> new similarity ratio feature

src/app/diagram/diagram.component.ts
=> newSimRatio

package-lock.json, package.json, src/app/app.component.ts, src/app/app.module.ts, src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.ts, src/environments/environment.ts, src/index.html
Reverts Malek-Jabareen/ICSD#53
=> Revert "First Database and Table, Read keywords from database"

src/app/diagram/diagram.component.html, src/app/diagram/diagram.component.ts
ignore  tabes & new lines options
=> pref options

src/app/diagram/diagram.component.ts
auto fit up to 6 windows and a bug was fixed when reopening the windows.
=> autoFitWindows
